### ISSUE TITLE
Commands not executing

### ISSUE THREAD

**Issue by conscnt1** [zThana/RacesOfThana#7]
- The /rot inspect command, executed immediately after a race change, results in an error about the absence of that race (+I also report that the message about race change is apparently missing in lang and therefore it's untranslatable).
![image](https://github.com/user-attachments/assets/e9ba123c-3347-4e61-b129-0778901204c6)
- Commands executed when night falls don't work - nor does the entire race command section in general (part of command module below). Even for basic races like ZIRA. It just doesn't do anything. No output to the console or error messages.
![image](https://github.com/user-attachments/assets/14ad7c04-b967-4b88-a2b3-3066c2bfe362)

**Comment by zThana** [comment]
I've fixed the inspect subcommand for in the next update.
I can't replicate your 2nd bug. Could you check your console for errors?

![image](https://github.com/user-attachments/assets/a6114cab-2a49-403e-95ec-c8452978e17c)

```yaml
commands:
  enabled: true
  day:
    - tellraw %player_name% {"text":"It turned day!","color":"green"}
  night:
    - execute at %player_name% run effect give @a[distance=..8] mining_fatigue 30 2 true
    - execute at %player_name% run effect give @a[distance=..8] weakness 60 2 true
    - execute at %player_name% run effect give @a[distance=..8] slowness 15 3 true
    - tellraw %player_name% {"text":"It turned night!","color":"blue"}
```
